"""
This module was autogenerated by gale.
"""
from src.hello_world import HelloWorld

if __name__ == '__main__':
    # HelloWorld takes every gale.game.Game argument (title, window
    # size, ...) straight from settings.py / gale.conf.global_settings,
    # so there's no need to pass any of them here -- see settings.py.
    game = HelloWorld()
    game.exec()
